#ifndef __CONST_MENU_EXTENDED_LIGIC__
#define __CONST_MENU_EXTENDED_LIGIC__

#define EKRAN_EXTENDED_LIGIC        (EKRAN_TIMEOUT_ANALOG_REGISTRATOR + 1)

#define MAX_ROW_FOR_EXTENDED_LIGIC  7

#define INDEX_OF_GENERAL_PICKUP_EL        0
#define INDEX_OF_DEFINED_FUNCTIONS        1
#define INDEX_OF_DEFINED_TRIGGERS         2
#define INDEX_OF_DEFINED_AND              3
#define INDEX_OF_DEFINED_OR               4
#define INDEX_OF_DEFINED_XOR              5
#define INDEX_OF_DEFINED_NOT              6

#endif
